# Generated by Django 2.1.4 on 2019-02-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='progress',
        ),
        migrations.AddField(
            model_name='order',
            name='consigneeAddr',
            field=models.CharField(default='无', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='consigneeName',
            field=models.CharField(default='无', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='consigneeTel',
            field=models.CharField(default='无', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='progressStr',
            field=models.CharField(default='', max_length=200),
        ),
    ]
