# Generated by Django 2.1.4 on 2019-02-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0004_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderstatus',
            field=models.CharField(default='待收货', max_length=5),
        ),
    ]
