# Generated by Django 2.1.4 on 2019-02-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='orderid',
            field=models.CharField(default='', max_length=40),
        ),
    ]
