# Generated by Django 2.1.4 on 2019-02-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0007_comment_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
